---
name: Build-CI

on:
  push:
    branches:
      - hotfix/*
      - bugfix/*
      - release/*
      - feature/*

  workflow_dispatch:


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Echo
      run: sleep 60
