---
name: Build-CI

on:
  push:
    branches:
      - hotfix/*
      - bugfix/*
      - release/*
      - feature/*

  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: acessando projeto e dando o git pull na branch
      run: cd /home/jayson/Documentos/teste-ci/homolog/teste-ci && git pull >> /tmp/homolog/history-homolog.txt
      
    - name: Verificando se funciona a minha variavel
      run: echo $GITHUB_REF_NAME
