---
name: Build-CI

on:
  push:
    branches:
      - hotfix/*
      - bugfix/*
      - release/*
      - feature/*

  workflow_dispatch:
  
jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: acessando projeto e dando o git pull na branch
    - uses: actions/checkout@v3
    - env:
        GITHUB_REF_NAME: $GITHUB_REF_NAME
      
      run: cd /home/jayson/Documentos/teste-ci/homolog/teste-ci && git pull >> /tmp/homolog/history-homolog.txt && echo $GITHUB_REF_NAME
