name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted
   
    steps:
    - uses: actions/checkout@v3
    - name: Echo
      run: cd /home/jayson/Documentos/teste-ci/prod/teste-ci && git pull >> /tmp/prod/history-prod.txt

