name: Deploy

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: self-hosted
   
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Echo
      run: sleep 60

