---
name: Build-CI

on:
  push:
    branches:
      - hotfix/*
      - bugfix/*
      - release/*
      - feature/*


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: acessando projeto e dando o git pull na master 
      run: cd /home/jayson/Documentos/teste-ci/prod/teste-ci && git pull >> /tmp/prod/history-prod.txt
